name: "Curio.sh"
description: "A data-first security scanner that finds risks and vulnerabilities in your code so you can protect sensitive data."
branding:
  icon: "check-square"
  color: "purple"
inputs:
  config-file:
    description: "Curio configuration file path"
    required: false
    default: ""
  only-rule:
    description: "Specify the comma-separated ids of the rules you would like to run. Skips all other rules."
    required: false
    default: ""
  skip-rule:
    description: "Specify the comma-separated ids of the rules you would like to skip. Runs all other rules."
    required: false
    default: ""
  skip-path:
    description: "Specify the comma separated files and directories to skip. Supports * syntax, e.g. --skip-path users/*.go,users/admin.sql"
    required: false
    default: ""
outputs:
  rule_breaches:
    description: "Details of any rule breaches that occur"
  exit_code:
    description: "exit code from curio binary"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - "--config-file=${{ inputs.config-file }}"
    - "--only-rule=${{ inputs.only-rule }}"
    - "--skip-rule=${{ inputs.skip-rule }}"
    - "--skip-path=${{ inputs.skip-path }}"
